plugin: aws_ec2

aws_access_key: AKIA4NICQXE4QF2EKZ5Y
aws_secret_key: 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

regions:
  - ap-south-1

filters:
  instance-state-name : running
 
keyed_groups:
  - key: tags.Name
    prefix: ""
    separator: ""

hostnames:
  - private-ip-address

compose:
  ansible_host: private_ip_address
